from enum import Enum
class ResponseSignal(str, Enum):
    FILE_TYPE_NOT_SUPPORTED = "file type not supported"
    FILE_SIZE_EXCEEDS_LIMIT = "file size exceeds limit"
    FILE_IS_VALID = "file is valid"
    FILE_UPLOAD_SUCCESS = "file uploaded successfully"
    FILE_UPLOAD_FAILED = "file upload failed"
    PROCESSING_SUCCESS = "file processed successfully"
    PROCESSING_FAILED = "file processing failed"  
    NO_FILES_TO_PROCESS = "no files to process"
    NO_FILE_ID_ERROR = "no file id provided"
    Project_NOT_FOUND = "project not found"
    VECTOR_DB_SEARCH_FAILED = "vector db search failed"
    VECTOR_DB_SEARCH_SUCCESS = "vector db search success"
    INSERT_INTO_VECTOR_DB_FAILED = "insert into vector db failed"
    INSERT_INTO_VECTOR_DB_SUCCESS = "insert into vector db success"
